"""
File: instruments.py
Purpose:
    Provide standardized mappings of instrument names appearing 
    in original MusicXML scores, including multilingual variants
    and part-specific labels (e.g., Violin I/II, Horn in F).
Author: Zih-Syuan Lin (2025)
"""

from typing import Final

INST_CLASSES:Final[dict[str,list]] = {
    'woodwinds': [
        'englishhorn', 'flute', 'piccolo', 'oboe', 'clarinet', 'bassoon', 'contrabassoon',   
    ],
    'brass': [
        'horn', 'piccolotrumpet', 'trumpet', 'trombone', 'basstrombone', 'tuba'
    ],
    'strings': [
        'violin', 'viola', 'violoncello', 'doublebass'
    ],
    'percussion': [
        'timpani', 'triangle', 'cymbal', 'tamtam', 'bassdrum'
    ],
    'voice': [
        'sopranosolo', 'sopranochoir', 'altosolo', 'altochoir',
        'tenorsolo', 'tenorchoir', 'baritonesolo', 'basschoir',  
    ]
}


INSTRUMENT_NAME:Final[list[str]] = [
    # woodwinds
    'englishhorn', 'flute', 'piccolo', 'oboe', 'clarinet', 
    'bassoon', 'contrabassoon',
    # brass
    'horn', 'piccolotrumpet', 'trumpet', 'trombone', 'basstrombone', 'tuba',
    # strings
    'violin', 'viola', 'violoncello', 'doublebass',
    # percussions
    'timpani', 'triangle', 'cymbal', 'tamtam', 'bassdrum',
    # voices
    'sopranosolo', 'sopranochoir', 'altosolo', 'altochoir',
    'tenorsolo', 'tenorchoir', 'baritonesolo', 'basschoir',
    # others
    'none'
]

INSTRUMENT_LOOKUP_TABLE:Final[dict[str,int]] = {}
for k,v in enumerate(INSTRUMENT_NAME):
    INSTRUMENT_LOOKUP_TABLE[v] = k
    if v!='other':
        INSTRUMENT_LOOKUP_TABLE[v+'1'] = k
        INSTRUMENT_LOOKUP_TABLE[v+'2'] = k
        INSTRUMENT_LOOKUP_TABLE[v+'3'] = k
        INSTRUMENT_LOOKUP_TABLE[v+'4'] = k
        INSTRUMENT_LOOKUP_TABLE[v+'1-1'] = k
        INSTRUMENT_LOOKUP_TABLE[v+'1-2'] = k
        INSTRUMENT_LOOKUP_TABLE[v+'2-1'] = k
        INSTRUMENT_LOOKUP_TABLE[v+'2-2'] = k
INSTRUMENT_LOOKUP_TABLE['hn2'] = INSTRUMENT_LOOKUP_TABLE['horn']
INSTRUMENT_LOOKUP_TABLE['hn4'] = INSTRUMENT_LOOKUP_TABLE['horn']
INSTRUMENT_LOOKUP_TABLE['violina1'] = INSTRUMENT_LOOKUP_TABLE['violin']
INSTRUMENT_LOOKUP_TABLE['violina2'] = INSTRUMENT_LOOKUP_TABLE['violin']
INSTRUMENT_LOOKUP_TABLE['violinb1'] = INSTRUMENT_LOOKUP_TABLE['violin']
INSTRUMENT_LOOKUP_TABLE['violinb2'] = INSTRUMENT_LOOKUP_TABLE['violin']

INSTRUMENT_NAME_VARIATION:Final[dict[str,str]] = {
    'Fl': 'flute',
    'Fl1': 'flute1',
    'Fl2': 'flute2',
    'Ob': 'oboe',
    'Ob1': 'oboe1',
    'Ob2': 'oboe2',
    'Cl': 'clarinet',
    'Cl1': 'clarinet1',
    'Cl2': 'clarinet2',
    'Fg': 'bassoon',
    'Fg1': 'bassoon1',
    'Fg2': 'bassoon2',
    'Hrn': 'horn',
    'Hrn1': 'horn1',
    'Hrn2': 'horn2',
    'HrnD': 'horn',
    'HrnF': 'horn',
    'HrnB': 'horn',
    'HrnEbI': 'horn1',
    'HrnEbII': 'horn2',
    'HrnEbIII': 'horn3',
    'Horn in B♭': 'horn',
    'Trp': 'trumpet',
    'Trp1': 'trumpet1',
    'Trp2': 'trumpet2',
    'Trb': 'trombone',
    'Timp': 'timpani',
    'Vln1': 'violin1',
    'Vln1a': 'violin1-1',
    'Vln1b': 'violin1-2',
    'Vln2': 'violin2',
    'Vla': 'viola',
    'Vc': 'violoncello',
    'Cb': 'doublebass',
    'Fløyte': 'flute',
    'FlÃ¸yte': 'flute',
    'Flute': 'flute',
    'Bassoon': 'bassoon',
    'Clarinet': 'clarinet',
    'Oboe': 'oboe',
    'Horn': 'horn',
    'Trumpet': 'trumpet',
    'Trombone': 'trombone',
    'Timpani': 'timpani',
    'Violin': 'violin',
    'Violin1': 'violin1',
    'Violin2': 'violin2',
    'Violins': 'violin',
    'Violins 1': 'violin1',
    'Violins 2': 'violin2',
    'Viola': 'viola',
    'Violas': 'viola',
    'Cello': 'violoncello',
    'Cellos': 'violoncello',
    'Violoncellos':'violoncello',
    'Contrabasses': 'doublebass',
    'Contrabass': 'doublebass',
    'Doublebass': 'doublebass',
    'Obo': 'oboe',
    'B♭-klarinett': 'clarinet',
    'A-klarinett': 'clarinet',
    'Bâ\x99\xad-klarinett': 'clarinet',
    'B♭ Clarinet': 'clarinet',
    'Bâ\x99\xad Clarinet': 'clarinet',
    'Fagott': "bassoon",
    'D-horn': 'horn',
    'B♭-basshorn ': 'horn',
    'Bâ\x99\xad-basshorn': 'horn',
    'Eâ\x99\xad-horn': 'horn',
    'F-horn': 'horn',
    'C-horn': 'horn',
    'E♭-horn': 'horn',
    'Horn in E♭': 'horn',
    'Horn in F': 'horn',
    'Horn in C': 'horn',
    'Horn in A': 'horn',
    'Horn in D': 'horn',
    'Horn in Bâ\x99\xad': 'horn',
    'Horn in Eâ\x99\xad': 'horn',
    'A-horn': 'horn',
    'D-trompet': 'trumpet',
    'C-trompet': 'trumpet',
    'E♭-trompet': 'trumpet',
    'F-trompet': 'trumpet',
    'Eâ\x99\xad-trompet': 'trumpet',
    'B♭ Trumpet': 'trumpet',
    'Bâ\x99\xad Trumpet': 'trumpet',
    'C Trumpet': 'trumpet',
    'D Trumpet': 'trumpet',
    'F Trumpet': 'trumpet',
    'E Trumpet': 'trumpet',
    'E♭ Trumpet': 'trumpet',
    'Pauker': 'timpani',
    'Fioliner': 'violin',
    'Fioliner': 'violin',
    'Bratsjer': 'viola',
    'Celloer': 'violoncello',
    'Violoncello': 'violoncello',
    'Kontrabasser': 'doublebass',
    'Contrabass': 'doublebass',
    'SopranoClarinet': 'clarinet',
    'Flauto': 'flute',
    'Clarinetti in B': 'clarinet',
    'Fagotti': 'bassoon',
    'Corni in Es': 'horn',
    'Corni in Fs': 'horn',
    'Corni in Cs': 'horn',
    'Corni in Ds': 'horn',
    'Corni in Bs': 'horn',
    'Horn in G': 'horn',
    'Corni': 'horn',
    'Oboi': 'oboe',
    'Corno in B': 'horn',
    'Corno in G': 'horn',
    'Trombe in Es': 'trumpet',
    'Timpani in Es. B.': 'timpani',
    'Violino I.': 'violin1',
    'Violino II.': 'violin2',
    'Contrabasso': 'doublebass',
    'Basso': 'doublebass',
    'Oboe I': 'oboe1',
    'Oboe II': 'oboe2',
    'Fagotto I': 'bassoon1',
    'Fagotto II': 'bassoon2',
    'Corno I in C': 'horn1',
    'Corno II in C': 'horn2',
    'Clarino I in C': 'piccolotrumpet1',
    'Clarino II in C': 'piccolotrumpet2',
    'Timpani in Câ\x80\x93G': 'timpani',
    'Violino I': 'violin1',
    'Violino II': 'violin2',
    # new
    'Fl': 'flute',
    'Fl1': 'flute1',
    'Fl2': 'flute2',
    'Ob': 'oboe',
    'Ob1': 'oboe1',
    'Ob2': 'oboe2',
    'Cl': 'clarinet',
    'Cl1': 'clarinet1',
    'Cl2': 'clarinet2',
    'Fg': 'bassoon',
    'Fg1': 'bassoon1',
    'Fg2': 'bassoon2',
    'Hrn': 'horn',
    'Hrn1': 'horn1',
    'Hrn2': 'horn2',
    'HrnD': 'horn',
    'HrnF': 'horn',
    'HrnB': 'horn',
    'HrnEbI': 'horn1',
    'HrnEbII': 'horn2',
    'HrnEbIII': 'horn3',
    'Horn in B♭': 'horn',
    'Trp': 'trumpet',
    'Trp1': 'trumpet1',
    'Trp2': 'trumpet2',
    'Trb': 'trombone',
    'Timp': 'timpani',
    'Vln1': 'violin1',
    'Vln1a': 'violin1-1',
    'Vln1b': 'violin1-2',
    'Vln2': 'violin2',
    'Vla': 'viola',
    'Vc': 'violoncello',
    'Cb': 'doublebass',
    'Fløyte': 'flute',
    'FlÃ¸yte': 'flute',
    'Flute': 'flute',
    'Bassoon': 'bassoon',
    'Clarinet': 'clarinet',
    'Oboe': 'oboe',
    'Horn': 'horn',
    'Trumpet': 'trumpet',
    'Trombone': 'trombone',
    'Timpani': 'timpani',
    'Violin': 'violin',
    'Violin1': 'violin1',
    'Violin2': 'violin2',
    'Violins': 'violin',
    'Violins 1': 'violin1',
    'Violins 2': 'violin2',
    'Viola': 'viola',
    'Violas': 'viola',
    'Cello': 'violoncello',
    'Cellos': 'violoncello',
    'Violoncellos':'violoncello',
    'Contrabasses': 'doublebass',
    'Contrabass': 'doublebass',
    'Doublebass': 'doublebass',
    'Obo': 'oboe',
    'B♭-klarinett': 'clarinet',
    'A-klarinett': 'clarinet',
    'Bâ\x99\xad-klarinett': 'clarinet',
    'B♭ Clarinet': 'clarinet',
    'Bâ\x99\xad Clarinet': 'clarinet',
    'Fagott': "bassoon",
    'D-horn': 'horn',
    'B♭-basshorn ': 'horn',
    'Bâ\x99\xad-basshorn': 'horn',
    'Eâ\x99\xad-horn': 'horn',
    'F-horn': 'horn',
    'C-horn': 'horn',
    'E♭-horn': 'horn',
    'Horn in E♭': 'horn',
    'Horn in F': 'horn',
    'Horn in C': 'horn',
    'Horn in A': 'horn',
    'Horn in D': 'horn',
    'Horn in Bâ\x99\xad': 'horn',
    'Horn in Eâ\x99\xad': 'horn',
    'A-horn': 'horn',
    'D-trompet': 'trumpet',
    'C-trompet': 'trumpet',
    'E♭-trompet': 'trumpet',
    'F-trompet': 'trumpet',
    'Eâ\x99\xad-trompet': 'trumpet',
    'B♭ Trumpet': 'trumpet',
    'Bâ\x99\xad Trumpet': 'trumpet',
    'C Trumpet': 'trumpet',
    'D Trumpet': 'trumpet',
    'F Trumpet': 'trumpet',
    'E Trumpet': 'trumpet',
    'E♭ Trumpet': 'trumpet',
    'Pauker': 'timpani',
    'Fioliner': 'violin',
    'Fioliner': 'violin',
    'Bratsjer': 'viola',
    'Celloer': 'violoncello',
    'Violoncello': 'violoncello',
    'Kontrabasser': 'doublebass',
    'Contrabass': 'doublebass',
    'SopranoClarinet': 'clarinet',
    'Flauto': 'flute',
    'Clarinetti in B': 'clarinet',
    'Fagotti': 'bassoon',
    'Corni in Es': 'horn',
    'Corni in Fs': 'horn',
    'Corni in Cs': 'horn',
    'Corni in Ds': 'horn',
    'Corni in Bs': 'horn',
    'Horn in G': 'horn',
    'Corni': 'horn',
    'Oboi': 'oboe',
    'Corno in B': 'horn',
    'Corno in G': 'horn',
    'Trombe in Es': 'trumpet',
    'Timpani in Es. B.': 'timpani',
    'Violino I.': 'violin1',
    'Violino II.': 'violin2',
    'Contrabasso': 'doublebass',
    'Basso': 'doublebass',
    'Oboe I': 'oboe1',
    'Oboe II': 'oboe2',
    'Fagotto I': 'bassoon1',
    'Fagotto II': 'bassoon2',
    'Corno I in C': 'horn1',
    'Corno II in C': 'horn2',
    'Clarino I in C': 'piccolotrumpet1',
    'Clarino II in C': 'piccolotrumpet2',
    'Timpani in Câ\x80\x93G': 'timpani',
    'Violino I': 'violin1',
    'Violino II': 'violin2',
    'horn12': 'horn',
    'horn34': 'horn',
    'trumpet12': 'trumpet',
    'violin1': 'violin1',
    'violin2': 'violin2',
}
INSTRUMENT_NAME_VARIATION.update({k:k for k in INSTRUMENT_LOOKUP_TABLE.keys()})